### ISSUE TITLE
Need of model parameters!

### ISSUE THREAD

**Issue by Nid989** [rvente/TeXNet.ai#4]
Hey, @rvente I've been working on this project referenced to Im2latex for 4 months but because of lack of computational power I'm unable to train it properly, so this is my humble request can you provide me the data reflecting your model, a naive one will also work. I just need to show it to my professors and classmates.

**Comment by rvente** [comment]
Hi, glad to lend a hand. As mentioned in our readme, this project based on  [untrix/im2latex](https://github.com/untrix/im2latex) by Sumeet S. Singh. The [project page](untrix.github.io/i2l/) is a gold-mine and contains just what you want: [model parameters](https://untrix.github.io/i2l/#model-weights) at the bottom of the page. One way to start would be going to Sumeet's repo and proceeding from there. Then you can dive into the model code to view how to load checkpoints and get the model up and running (for inference).

For training, [Google Cloud](https://cloud.google.com/) and other providers might have promotional credit for students starting a new account. This was the method I used to train: it cost $120 of credits to train the whole model.

**Comment by Nid989** [comment]
🤗  just forgot to thank you,
Indeed I created a model inspired by Sumeet Singh Repo using PyTorch and
used Vision transformer and the results were really good.
